# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5daa7743c595ec06f7bd74aa5d44bcbba442f8c61f9e264d8290532296110bed2cec3dd45795f1b6316bd0499879baf5e15e863c62f9807814b182e84dbfe16e

test:
  secret_key_base: b8c3e01d72dcedf1c95f7dda60852c6600ba21b24bf700d558ad9dceec2f9bf946e6c06a815134bd75dcdb39085d20adc52d96d9f5d82626c82a1eae24a621c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
